version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=challengedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challengenet

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    tty: true
    networks:
      - challengenet
    depends_on:
      - db

  
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks:
      - challengenet
    ports: 
      - "8080:80"
    depends_on:
      - app

networks:
  challengenet:
    driver: bridge